name: Migrations
on: 
  push:
    branches:
      - main
jobs:
  migrations: 
      name: Run pending migrations against the production database
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: 14.x

        - name: Install deps and build (with cache)
          uses: bahmutov/npm-install@v1

        - name: Run Migrations
          env: 
            DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
          run: "DATABASE_URL=$DATABASE_URL npx prisma migrate deploy"